[package]
name = "open_scape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "*"

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["image", "ttf"]
